version: '3.2'

volumes:
  postgresqlDataXVol:
    driver: local
    driver_opts:
      type: none
      o: bind
      device: "/var/lib/postgres/dbztest/data"
  postgresqlLogsXVol:
    driver: local
    driver_opts:
      type: none
      o: bind
      device: "/var/lib/postgres/dbztest"

services:
  postgresql:
    # Use debezium/postgres:11 or debezium/postgres:11-alpine to test debezium 0.9.1.Final 
    image: debezium/postgres:9.6
    hostname: postgresql
    ports:
      - 5434:5432
    environment:
      - POSTGRES_PASSWORD=${PGPASSWORD}
      - POSTGRES_DB=dbztest
      - POSTGRES_USER=postgres
    volumes:
      - postgresqlDataXVol:/var/lib/postgresql/data 
      - postgresqlLogsXVol:/var/log/postgresql
